{
  description = "Pi Agent Rust - AI Coding Agent CLI";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    rust-overlay.url = "github:oxalica/rust-overlay";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, rust-overlay, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        overlays = [ (import rust-overlay) ];
        pkgs = import nixpkgs { inherit system overlays; };
        nightlyRust = pkgs.rust-bin.nightly.latest.default;
      in {
        packages = {
          pi-agent-rust = pkgs.rustPlatform.buildRustPackage {
            pname = "pi-agent-rust";
            version = "0.1.10";
            src = ./.;
            cargoLock.lockFile = ./Cargo.lock;
            vendorDir = ./vendor;
            nativeBuildInputs = with pkgs; [ pkg-config sqlite nightlyRust ];
            buildInputs = with pkgs; [ openssl ];
            doCheck = true;
            patchPhase = ''
              MODELS_TS="legacy_pi_mono_code/pi-mono/packages/ai/src/models.generated.ts"
              if [ ! -f "$MODELS_TS" ]; then
                echo "Creating stub for missing: $MODELS_TS"
                mkdir -p "$(dirname "$MODELS_TS")"
                printf '%s\n' "// Stub generated by Nix" "export const MODELS = {} as const;" > "$MODELS_TS"
              fi
            '';
          };
          default = self.packages.${system}.pi-agent-rust;
        };

        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [
            (rust-bin.nightly.latest.default.override {
              extensions = [ "rust-src" "rustfmt" "clippy" ];
              targets = [
                "x86_64-unknown-linux-gnu"
              ];
            })
            pkg-config
            sqlite
            openssl
            openssl.dev
            git
            gcc
          ];

          shellHook = ''
            export OPENSSL_DIR=${pkgs.openssl.dev}
            export OPENSSL_LIB_DIR=${pkgs.openssl.out}/lib
            export OPENSSL_INCLUDE_DIR=${pkgs.openssl.dev}/include
            export PKG_CONFIG_PATH=${pkgs.openssl.dev}/lib/pkgconfig:$PKG_CONFIG_PATH
            echo "🚀 Pi Agent Rust Dev Environment Ready"
          '';
        };
      });
}